# Generated by Django 5.0.7 on 2024-10-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_recipe_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=50000)),
                ('unit', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=1000)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.recipe')),
            ],
        ),
    ]
